# Generated by Django 5.0 on 2023-12-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskrequest',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
