version: '3'
services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: almau_crm_bot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    command: 
      - gunicorn Almau_Advisor.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DEBUG=False
      - DATABASE_HOST=db
      - DATABASE_NAME=almau_crm_bot
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=qwerty123
      - DATABASE_PORT=5432

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
