# Generated by Django 4.2.2 on 2023-11-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_ids", models.TextField(help_text="Comma separated chat IDs")),
                ("message", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="mailings/"),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
