# Generated by Django 4.2.2 on 2023-10-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="conversation",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
