# Generated by Django 5.0 on 2023-12-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0002_studentimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentimport',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
