# Generated by Django 4.2.2 on 2023-10-19 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0002_question_conversation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="text",
        ),
    ]
