# Generated by Django 4.2.2 on 2023-10-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0003_remove_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
