# Generated by Django 4.2.2 on 2023-11-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0003_rename_sent_at_mailing_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="mailings/"),
        ),
    ]
