# Generated by Django 4.2.2 on 2023-10-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0004_question_mobile_question_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="question",
            name="name",
        ),
        migrations.AddField(
            model_name="question",
            name="course",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="specialty",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
