# Generated by Django 4.2.2 on 2023-10-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0005_remove_question_mobile_remove_question_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
