# Generated by Django 4.2.2 on 2023-10-23 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0008_rename_first_name_student_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Advisor.specialty",
            ),
        ),
    ]
