# Generated by Django 4.2.2 on 2023-10-23 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0009_alter_student_specialty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="course",
        ),
        migrations.RemoveField(
            model_name="question",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="question",
            name="specialty",
        ),
        migrations.RemoveField(
            model_name="student",
            name="authenticated",
        ),
        migrations.RemoveField(
            model_name="student",
            name="questions_asked",
        ),
    ]
