# Generated by Django 4.2.2 on 2023-10-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0010_remove_question_course_remove_question_full_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
        ),
    ]
