# Generated by Django 4.2.2 on 2023-10-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0011_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
