# Generated by Django 4.2.2 on 2023-10-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0013_remove_request_assigned_user_question_assigned_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="request",
        ),
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Новая"),
                    ("IN_PROCESS", "В обработке"),
                    ("CLOSED", "Закрыта"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Request",
        ),
    ]
