# Generated by Django 4.2.2 on 2023-10-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Advisor", "0015_alter_question_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.TextField(),
        ),
    ]
