# Generated by Django 4.2.2 on 2023-11-03 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Help_Desk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpdeskrequest",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
